install:
 - pip install -r requirements-travis.txt
 - test `python -c 'import sys; print(1 if sys.version_info.major >=3 and sys.version_info.minor < 4 else 0)'` -eq 1 && pip install -U 'sphinx<1.5' || echo ''
language: python
python:
 - 3.3
 - 3.4
 - 3.5
 - 3.6
script:
 - python tests.py -a
 - flake8 sphobjinv
 - cd doc
 - make doctest

