install:
 - pip install -r requirements-travis.txt
language: python
python:
 - 3.4
 - 3.5
 - 3.6
script:
 - coverage run tests.py -a
 - flake8 sphobjinv
 - cd doc
 - make doctest
 - cd ..
 - echo $TRAVIS_PYTHON_VERSION | grep -e '^3\.5' && codecov || echo "No codecov."

