install:
 - pip install -U pip setuptools
 - pip install -U --force-reinstall -r requirements-travis.txt
 - sh -c 'cd doc; make html; mkdir scratch'
language: python
python:
 - 3.4
 - 3.5
 - 3.6
 - 3.7-dev
script:
 - python --version
 - pip list
 - pytest --cov=src --testall --nonloc
 - do_rest=$( echo $TRAVIS_PYTHON_VERSION | grep -e '^3\.6' | wc -l )
 - if [ $do_rest -gt 0 ]; then pip install black; black --check .; else echo "No black."; fi
 - if [ $do_rest -gt 0 ]; then sh -c 'cd doc; make doctest'; else echo "No doctest."; fi
 - if [ $do_rest -gt 0 ]; then codecov; else echo "No codecov."; fi

